# Assign specific workspaces to each monitor
workspace=1,monitor:desc:AU Optronics 0x223D
workspace=2,monitor:desc:Lenovo Group Limited LEN LI2231wA 30486D2721634
workspace=3,monitor:desc:AU Optronics 0x223D
workspace=4,monitor:desc:AU Optronics 0x223D
