# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2D2C2E)
$foreground = rgb(FAF5F0)
$color0 = rgb(525153)
$color1 = rgb(27252D)
$color2 = rgb(5A4945)
$color3 = rgb(454F65)
$color4 = rgb(5A6A8B)
$color5 = rgb(8A7256)
$color6 = rgb(B5A99F)
$color7 = rgb(F0E8E1)
$color8 = rgb(A8A29E)
$color9 = rgb(34313B)
$color10 = rgb(78625C)
$color11 = rgb(5D6987)
$color12 = rgb(788EB9)
$color13 = rgb(B89873)
$color14 = rgb(F1E1D4)
$color15 = rgb(F0E8E1)
